import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/home/header"
import Footer from "@/components/home/footer"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Salimov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-900 container mx-auto px-8">
        <div className="">
          <Header />
          <main className="flex justify-center">{children}</main>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
